'use client';
import dynamic from 'next/dynamic';
import { FormEvent, useState } from 'react';
const Scene3D = dynamic(() => import('./Scene3D'), { ssr:false });
type Profile={name:string;role:string;bio:string;born:string;agency:string;awards:string}|null; type Work={id:number;title:string;year:string;kind:string;role:string;poster:string}; type Photo={id:number;src:string;caption:string};
export default function Portfolio({profile,works,photos}:{profile:Profile;works:Work[];photos:Photo[]}) { const [status,setStatus]=useState(''); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))}); setStatus(r.ok?'Pesan terkirim. Terima kasih.':'Gagal. Periksa form lalu coba lagi.'); if(r.ok)e.currentTarget.reset();}; const p=profile ?? {name:'Go Youn-jung',role:'Actor · Artist · Muse',bio:'Korean actor with a magnetic screen presence.',born:'Seoul, Korea',agency:'MMA Entertainment',awards:'Rising Star'}; return <main>
<header><a className="brand" href="#top">GYJ<span>_</span></a><nav><a href="#about">Profile</a><a href="#works">Selected work</a><a href="#contact">Contact</a></nav></header>
<section id="top" className="hero"><div className="hero-copy"><p className="eyebrow">Official archive · 2026</p><h1>{p.name}</h1><p className="role">{p.role}</p><p className="intro">A living archive, told through motion, character, and stillness.</p><a className="button" href="#works">Explore work <b>↓</b></a></div><div className="scene"><Scene3D images={photos.map(x=>x.src)}/><p className="drag">Drag cursor to orbit archive</p></div></section>
<section id="about" className="about"><p className="eyebrow">01 / Profile</p><div><h2>Presence<br/>in every frame.</h2><p>{p.bio}</p><dl><div><dt>Born</dt><dd>{p.born}</dd></div><div><dt>Representation</dt><dd>{p.agency}</dd></div><div><dt>Recognition</dt><dd>{p.awards}</dd></div></dl></div></section>
<section id="works" className="works"><p className="eyebrow">02 / Selected work</p><h2>Characters that<br/>stay with you.</h2><div className="work-grid">{works.map(w=><article className="work" key={w.id}><img src={w.poster} alt={w.title}/><div><p>{w.year} · {w.kind}</p><h3>{w.title}</h3><span>{w.role}</span></div></article>)}</div></section>
<section className="archive"><p className="eyebrow">03 / Image archive</p><div className="archive-grid">{photos.map(x=><figure key={x.id}><img src={x.src} alt={x.caption}/><figcaption>{x.caption}</figcaption></figure>)}</div></section>
<section id="contact" className="contact"><p className="eyebrow">04 / Inquiries</p><div><h2>Begin<br/>conversation.</h2><form onSubmit={submit}><input name="name" placeholder="Name" required/><input name="email" type="email" placeholder="Email" required/><textarea name="content" placeholder="Message" required rows={4}/><button>Send inquiry <b>↗</b></button>{status&&<p className="status">{status}</p>}</form></div></section>
<footer><span>© 2026 GYJ Archive</span><span>Built for screen &amp; motion</span></footer></main> }
